config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :companies, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :users, only: [:index]
  end

  resources :tweets, only: [:index]

  resources :users, param: :username, only: [:index, :show] do
    resources :tweets, only: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user, optional: true

  def self.cursor_paginate(cursor: nil, limit:)
    query = order(created_at: :desc)
    query = query.where("id < ?", cursor) if cursor.present?
    query.limit(limit)
  end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :company

  has_many :tweets, dependent: :destroy

  validates :username, presence: true, uniqueness: { case_sensitive: false }

  scope :by_company, -> (identifier) { where(company: identifier) if identifier.present? }
  scope :like_username, -> (username) { where('username LIKE ?', "%#{username}%") if username.present? }
  scope :by_username, -> (username) { where(username: username) }

  after_create :send_welcome_email

  private

  def send_welcome_email
    UserMailer.welcome(self).deliver_later
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
end

app/controllers/companies_controller.rb
class CompaniesController < ActionController::Base
  layout 'application'

  before_action :set_company, only: [:show, :edit, :update, :destroy]

  def index
    @companies = Company.all
  end

  def show
  end

  def new
    @company = Company.new
  end

  def edit
  end

  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to @company, notice: 'Company was successfully created.'
    else
      render :new
    end
  end

  def update
    if @company.update(company_params)
      redirect_to @company, notice: 'Company was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @company.destroy
    redirect_to companies_url, notice: 'Company was successfully deleted.'
  end

  private

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:name)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    tweets = if params[:user_username].present?
              user_tweets
            else
              Tweet
            end

    if tweets.any?
      tweets = tweets.cursor_paginate(
        cursor: params[:cursor],
        limit: self.class.per_page
      )
    end

    render json: {
      tweets: tweets,
      next_cursor: tweets&.last&.id
    }
  end

  private

  def user_tweets
    user = User.by_username(params[:user_username]).take
    user&.tweets || []
  end

  def self.per_page
    20
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    users = User
              .by_company(params[:company_id])
              .like_username(search_params[:username])
    render json: users.all
  end

  private

  def search_params
    params.permit(:username)
  end

end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Edit Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr id="<%= dom_id(company) %>">
        <td><%= company.name %></td>
        <td>
          <%= link_to 'Show', company %>
          <%= link_to 'Edit', edit_company_path(company) %>
          <button onclick="deleteCompany('<%= company_path(company) %>', '<%= form_authenticity_token %>')">Delete</button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

<script>
function deleteCompany(url, token) {
  if (confirm('Do you want to delete?')) {
    fetch(url, {
      method: 'DELETE',
      headers: {
        'X-CSRF-Token': token,
        'Content-Type': 'application/json'
      }
    }).then(function() {
      window.location.reload();
    });
  }
}
</script>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleApi</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <%= render 'shared/flash' %>
  <%= yield %>
</body>
</html>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <div class="flash-messages">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger' %>">
        <%= msg %>
      </div>
    <% end %>
  </div>
<% end %>